<map version="1.0.1">
<!-- To view this file, download free mind mapping software FreeMind from http://freemind.sourceforge.net -->
<node COLOR="#000000" CREATED="1421503196583" ID="ID_1462460097" LINK="System%20Administration.mm" MODIFIED="1421503224521" TEXT="CentOS">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="20"/>
<hook NAME="accessories/plugins/AutomaticLayout.properties"/>
<node COLOR="#0033ff" CREATED="1435149627724" ID="ID_239994505" MODIFIED="1436107961199" POSITION="right" TEXT="7">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1455721358841" ID="ID_1837839639" MODIFIED="1455721365200" TEXT="Virtualization">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1440935783891" FOLDED="true" ID="ID_1073361687" LINK="https://wiki.centos.org/HowTos/KVM" MODIFIED="1546199718456" TEXT="KVM">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1440935801911" ID="ID_1584462684" MODIFIED="1455721373003" TEXT="yum -y install @virt* dejavu-lgc-* xorg-x11-xauth tigervnc libguestfs-tools policycoreutils-python bridge-utils">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1440935894261" ID="ID_1265264002" MODIFIED="1455721373003" TEXT="semanage fcontext -a -t virt_image_t &quot;/vm(/.*)?&quot;; restorecon -R /vm ">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1440935899397" ID="ID_5451815" MODIFIED="1455721373003" TEXT="sed -i &apos;s/^\(net.ipv4.ip_forward =\).*/\1 1/&apos; /etc/sysctl.conf; sysctl -p ">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1440935905461" ID="ID_923208888" MODIFIED="1455721373004" TEXT="chkconfig libvirtd on; shutdown -r now">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1440935918209" ID="ID_1521732607" MODIFIED="1455721373004">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      chkconfig network on
    </p>
    <p>
      service network restart
    </p>
    <p>
      yum -y erase NetworkManager
    </p>
    <p>
      cp -p /etc/sysconfig/network-scripts/ifcfg-{eth0,br0}
    </p>
    <p>
      sed -i -e'/HWADDR/d' -e'/UUID/d' -e's/eth0/br0/' -e's/Ethernet/Bridge/' \
    </p>
    <p>
      /etc/sysconfig/network-scripts/ifcfg-br0
    </p>
    <p>
      echo DELAY=0 &gt;&gt; /etc/sysconfig/network-scripts/ifcfg-br0
    </p>
    <p>
      echo 'BOOTPROTO=&quot;none&quot;' &gt;&gt; /etc/sysconfig/network-scripts/ifcfg-eth0
    </p>
    <p>
      echo BRIDGE=br0 &gt;&gt; /etc/sysconfig/network-scripts/ifcfg-eth0
    </p>
    <p>
      service network restart
    </p>
    <p>
      brctl show
    </p>
  </body>
</html></richcontent>
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1465755894279" ID="ID_808865391" MODIFIED="1465755895427" TEXT="ifcfg-bridge0">
<node COLOR="#111111" CREATED="1447880029582" ID="ID_1851330091" MODIFIED="1447880034449">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      DEVICE=&quot;bridge0&quot;
    </p>
    <p>
      ONBOOT=&quot;yes&quot;
    </p>
    <p>
      BOOTPROTO=dhcp
    </p>
    <p>
      TYPE=Bridge
    </p>
    <p>
      NM_CONTROLLED=NO
    </p>
    <p>
      DELAY=0
    </p>
  </body>
</html></richcontent>
</node>
</node>
<node COLOR="#111111" CREATED="1465755911907" ID="ID_317123593" MODIFIED="1465755916634" TEXT="ifcfg-enp11s0">
<node COLOR="#111111" CREATED="1447880004642" ID="ID_201594783" MODIFIED="1447880014393">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      # Generated by dracut initrd
    </p>
    <p>
      NAME=&quot;enp11s0&quot;
    </p>
    <p>
      DEVICE=&quot;enp11s0&quot;
    </p>
    <p>
      ONBOOT=yes
    </p>
    <p>
      NETBOOT=yes
    </p>
    <p>
      UUID=&quot;d017778c-b91f-4853-8393-d014d24f5229&quot;
    </p>
    <p>
      IPV6INIT=yes
    </p>
    <p>
      BOOTPROTO=dhcp
    </p>
    <p>
      TYPE=Ethernet
    </p>
    <p>
      BRIDGE=bridge0
    </p>
    <p>
      NM_CONTROLLED=NO
    </p>
  </body>
</html></richcontent>
</node>
</node>
</node>
<node COLOR="#111111" CREATED="1453042290286" ID="ID_772163710" MODIFIED="1469457654447" TEXT="/var/lib/libvirt/images">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1457553520299" ID="ID_1400430680" MODIFIED="1469457654447" TEXT="/etc/libvirt/qemu/autostart">
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
<node COLOR="#990000" CREATED="1440504140480" FOLDED="true" ID="ID_423703538" MODIFIED="1545599035865" TEXT="Docker">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1440504201607" ID="ID_1758153499" LINK="http://www.liquidweb.com/kb/how-to-install-docker-on-centos-7/" MODIFIED="1542314148180" TEXT="Install">
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1440504148588" ID="ID_812096522" MODIFIED="1440504214436" TEXT="yum -y install docker docker-registry">
<font NAME="SansSerif" SIZE="12"/>
<icon BUILTIN="full-1"/>
</node>
<node COLOR="#111111" CREATED="1440504159875" ID="ID_1122722986" MODIFIED="1440504215872" TEXT="systemctl enable docker.service">
<font NAME="SansSerif" SIZE="12"/>
<icon BUILTIN="full-2"/>
</node>
<node COLOR="#111111" CREATED="1440504165083" ID="ID_63869001" MODIFIED="1440504217367" TEXT="systemctl start docker.service">
<font NAME="SansSerif" SIZE="12"/>
<icon BUILTIN="full-3"/>
</node>
<node COLOR="#111111" CREATED="1440504172239" ID="ID_432510743" MODIFIED="1440504220555" TEXT="systemctl status docker.service">
<font NAME="SansSerif" SIZE="12"/>
<icon BUILTIN="full-4"/>
</node>
</node>
</node>
<node COLOR="#990000" CREATED="1455210403008" ID="ID_1408661389" MODIFIED="1546199712271" TEXT="Xen">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1455222440581" ID="ID_1905169088" MODIFIED="1455721373011" TEXT="Installation">
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1455210412860" ID="ID_1613490466" MODIFIED="1455222449844" TEXT="yum install centos-release-xen">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1455210420840" ID="ID_807023945" MODIFIED="1455222449844" TEXT="yum update">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1455210428036" ID="ID_960890306" MODIFIED="1455222449845" TEXT="yum install xen">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1455211197001" ID="ID_655969713" MODIFIED="1455222449845" TEXT="yum install libvirt">
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
<node COLOR="#111111" CREATED="1545599415557" ID="ID_1705576624" MODIFIED="1545599420388" TEXT="yum">
<node COLOR="#111111" CREATED="1545599425826" ID="ID_1403307400" MODIFIED="1545599446795" TEXT="install yum-plugin-priorities"/>
<node COLOR="#111111" CREATED="1545599425827" ID="ID_168512479" MODIFIED="1545599464082" TEXT="centos-virt-xen-48">
<node COLOR="#111111" CREATED="1545599425827" ID="ID_1489060519" MODIFIED="1545599474268" TEXT="priority=10"/>
</node>
</node>
<node COLOR="#111111" CREATED="1458646897274" ID="ID_894637008" MODIFIED="1545598856588" TEXT="7.x">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1445481422313" ID="ID_1434336122" MODIFIED="1545598856588" TEXT="cobbler">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1449752170505" ID="ID_77431057" MODIFIED="1530133400958" TEXT="/usr/lib/python2.7/site-packages/koan">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1445481530374" ID="ID_1269279521" MODIFIED="1453809029886" TEXT="utils.py ">
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1445481537707" ID="ID_1071159605" MODIFIED="1445513042956">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      def check_version_greater_or_equal(version1, version2):
    </p>
    <p>
      <b><i>&#160;&#160;&#160;&#160;#ass = version1.split(&quot;.&quot;) </i></b>
    </p>
    <p>
      <b><i>&#160;&#160;&#160;&#160;#bss = version2.split(&quot;.&quot;) </i></b>
    </p>
    <p>
      <b><i>&#160;&#160;&#160;&#160;#if len(ass) != len(bss): </i></b>
    </p>
    <p>
      <b><i>&#160;&#160;&#160;&#160;#&#160;&#160;&#160;&#160;raise Exception(&quot;expected version format differs&quot;) </i></b>
    </p>
    <p>
      <b><i>&#160;&#160;&#160;&#160;#for i, a in enumerate(ass): </i></b>
    </p>
    <p>
      <b><i>&#160;&#160;&#160;&#160;#&#160;&#160;&#160;&#160;a = int(a) </i></b>
    </p>
    <p>
      <b><i>&#160;&#160;&#160;&#160;#&#160;&#160;&#160;&#160;b = int(bss[i]) </i></b>
    </p>
    <p>
      <b><i>&#160;&#160;&#160;&#160;#&#160;&#160;&#160;&#160;if a &lt; b: </i></b>
    </p>
    <p>
      <b><i>&#160;&#160;&#160;&#160;#&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return False</i></b>
    </p>
    <p>
      &#160;&#160;&#160;&#160;return True
    </p>
  </body>
</html></richcontent>
</node>
</node>
<node COLOR="#111111" CREATED="1445481426298" ID="ID_1510802972" MODIFIED="1453809029886" TEXT="virtinstall.py">
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1445481467515" ID="ID_1730857345" MODIFIED="1445513035243">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      &#160;&#160;&#160;&#160;if breed and breed != &quot;other&quot;:
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if os_version and os_version != &quot;other&quot;:
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if breed == &quot;suse&quot;:
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;suse_version_re = re.compile(&quot;^(opensuse[0-9]+)\.([0-9]+)$&quot;)
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if suse_version_re.match(os_version):
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;os_version = suse_version_re.match(os_version).groups()[0]
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;# make sure virt-install knows about our os_version,
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;# otherwise default it to virtio26 or generic26
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;found = False
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if os_version not in supported_variants:
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if &quot;virtio26&quot; in supported_variants:
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;os_version = &quot;virtio26&quot;
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;else:
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<b><i>#os_version = &quot;generic26&quot; </i></b>
    </p>
    <p>
      <b><i>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;os_version = &quot;rhel7.0&quot;</i></b>
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;print(&quot;- warning: virt-install doesn't know this os_version, &quot;
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&quot;defaulting to %s&quot; % os_version)
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;cmd += &quot;--os-variant %s &quot; % os_version
    </p>
  </body>
</html></richcontent>
</node>
</node>
<node COLOR="#111111" CREATED="1523808846729" ID="ID_915419677" MODIFIED="1545598913423" TEXT="internal error: unsupported input bus usb">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1523808888016" ID="ID_611818274" MODIFIED="1523808890636" TEXT="virtinstall.py">
<node COLOR="#111111" CREATED="1523808897892" ID="ID_933000740" MODIFIED="1523808912379">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      cmd = &quot;virt-install <b><i><u>--input keyboard</u></i></b>&#160;&quot;&#160;
    </p>
  </body>
</html></richcontent>
</node>
</node>
</node>
<node COLOR="#111111" CREATED="1523807957910" ID="ID_701748200" MODIFIED="1545598913422" TEXT="xen package needs to be installed">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1449751164509" ID="ID_297540647" MODIFIED="1523808878057" TEXT="app.py">
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1449751199353" ID="ID_1120059142" MODIFIED="1449751230108">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      if self.virt_type in [ &quot;xenpv&quot;, &quot;xenfv&quot; ]:
    </p>
    <p>
      cmd = sub_process.Popen(&quot;uname -r&quot;, stdout=sub_process.PIPE, shell=True)
    </p>
    <p>
      uname_str = cmd.communicate()[0]
    </p>
    <p>
      # correct kernel on dom0?
    </p>
    <p>
      #if uname_str &lt; &quot;2.6.37&quot; and uname_str.find(&quot;xen&quot;) == -1:
    </p>
    <p>
      #&#160;&#160;&#160;raise InfoException(&quot;kernel &gt;= 2.6.37 or kernel-xen needs to be in use&quot;)
    </p>
    <p>
      # xend installed?
    </p>
    <p>
      #if not os.path.exists(&quot;/usr/sbin/xend&quot;):
    </p>
    <p>
      #&#160;&#160;&#160;raise InfoException(&quot;xen package needs to be installed&quot;)
    </p>
    <p>
      # xend running?
    </p>
    <p>
      #rc = sub_process.call(&quot;/usr/sbin/xend status&quot;, stderr=None, #stdout=None, shell=True)
    </p>
    <p>
      #if rc != 0:
    </p>
    <p>
      #&#160;&#160;&#160;raise InfoException(&quot;xend needs to be started&quot;)
    </p>
  </body>
</html></richcontent>
</node>
</node>
</node>
</node>
<node COLOR="#111111" CREATED="1457269653653" ID="ID_1459850970" MODIFIED="1518903420046" TEXT="xen">
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1458984507567" ID="ID_1936304132" MODIFIED="1518900683010" TEXT="/usr/share/virt-manager/virtinst">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1518900652427" ID="ID_1654305268" MODIFIED="1518900664472" TEXT="urlfetcher.py">
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1458984535042" ID="ID_1208736234" MODIFIED="1518900642133">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      class GenericDistro(Distro):
    </p>
    <p>
      &#160;&#160;&#160;&#160;&quot;&quot;&quot;
    </p>
    <p>
      &#160;&#160;&#160;&#160;Generic distro store. Check well known paths for kernel locations
    </p>
    <p>
      &#160;&#160;&#160;&#160;as a last resort if we can't recognize any actual distro
    </p>
    <p>
      &#160;&#160;&#160;&#160;&quot;&quot;&quot;
    </p>
    <p>
      
    </p>
    <p>
      &#160;&#160;&#160;&#160;name = &quot;Generic&quot;
    </p>
    <p>
      &#160;&#160;&#160;&#160;os_variant = &quot;linux&quot;
    </p>
    <p>
      &#160;&#160;&#160;&#160;uses_treeinfo = True
    </p>
    <p>
      
    </p>
    <p>
      &#160;&#160;&#160;&#160;_xen_paths = [(&quot;images/xen/vmlinuz&quot;,
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&quot;images/xen/initrd.img&quot;),&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;# Fedora
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;]
    </p>
    <p>
      &#160;&#160;&#160;&#160;_hvm_paths = [(&quot;images/pxeboot/vmlinuz&quot;,
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&quot;images/pxeboot/initrd.img&quot;),&#160;&#160;&#160;&#160;&#160;&#160;&#160;# Fedora
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;]
    </p>
    <p>
      &#160;&#160;&#160;&#160;_iso_paths = [&quot;images/boot.iso&quot;,&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;# RH/Fedora
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&quot;boot/boot.iso&quot;,&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;# Suse
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&quot;current/images/netboot/mini.iso&quot;,&#160;&#160;&#160;# Debian
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&quot;install/images/boot.iso&quot;,&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;# Mandriva
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;]
    </p>
    <p>
      &#160;&#160;&#160; <b><i>_xen_paths = _hvm_paths</i></b>
    </p>
  </body>
</html></richcontent>
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
</node>
</node>
</node>
<node COLOR="#111111" CREATED="1538576733313" ID="ID_555422988" MODIFIED="1545599507097" TEXT="Logging">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1538576736772" ID="ID_143198580" MODIFIED="1545599507097" TEXT="/var/log/libvirt/libxl/libxl-driver.log">
<edge STYLE="bezier" WIDTH="thin"/>
<linktarget COLOR="#b0b0b0" DESTINATION="ID_143198580" ENDARROW="Default" ENDINCLINATION="299;0;" ID="Arrow_ID_322333847" SOURCE="ID_1217164145" STARTARROW="None" STARTINCLINATION="299;0;"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1538576869304" ID="ID_1217164145" MODIFIED="1545599507098" TEXT="ERROR    internal error: libxenlight failed to create new domain &apos;[VM name]&apos; ">
<arrowlink DESTINATION="ID_143198580" ENDARROW="Default" ENDINCLINATION="299;0;" ID="Arrow_ID_322333847" STARTARROW="None" STARTINCLINATION="299;0;"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
</node>
<node COLOR="#111111" CREATED="1387296666581" FOLDED="true" ID="ID_1872438747" MODIFIED="1545598856586" TEXT="6.x">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1387296672564" ID="ID_279233932" MODIFIED="1545598856587" TEXT="grub-bootxen.sh">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1387296682351" ID="ID_1155533640" MODIFIED="1518903412795" TEXT="Ensures kernel is loaded with correct Xen work.">
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
<node COLOR="#111111" CREATED="1389120680184" ID="ID_1201227542" MODIFIED="1545598856587" TEXT="Cobbler">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1389120682889" ID="ID_567569836" MODIFIED="1518903412796" TEXT="Disable reboot for VMs">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1389120691609" ID="ID_1846247604" MODIFIED="1518903412796" TEXT="xl delete [vm name]">
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1389120718075" ID="ID_450224368" MODIFIED="1389120733405" TEXT="Note:  not &quot;xm&quot; but &quot;xl&quot;"/>
</node>
<node COLOR="#111111" CREATED="1389120699704" ID="ID_1055488358" MODIFIED="1518903412796" TEXT="Create config file">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1389120703825" ID="ID_1818198942" MODIFIED="1518903412796" TEXT="xl create [vm name]">
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
</node>
</node>
</node>
<node COLOR="#00b439" CREATED="1455721376896" ID="ID_1664993921" MODIFIED="1542314128199" TEXT="chrome">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1455721410480" ID="ID_1896776134" MODIFIED="1455721424314" TEXT="yum install https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm -y">
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
<node COLOR="#00b439" CREATED="1436107963555" ID="ID_1733189226" MODIFIED="1436107971854" TEXT="nmcli d">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
</node>
<node COLOR="#0033ff" CREATED="1435149640460" ID="ID_875080470" LINK="http://wiki.centos.org/TipsAndTricks/MultimediaOnCentOS7" MODIFIED="1542314057927" POSITION="left" TEXT="multimedia">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1435149562817" ID="ID_1996954012" MODIFIED="1455210394925" TEXT="yum">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1435149621372" ID="ID_1246307121" MODIFIED="1455210394925" TEXT="groupinstall">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1435151021179" ID="ID_59726647" MODIFIED="1435151023289" TEXT="&apos;KDE Plasma Workspaces&apos;"/>
</node>
<node COLOR="#990000" CREATED="1435149565028" ID="ID_709786252" MODIFIED="1455210394926" TEXT="install">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1435149550777" ID="ID_312291180" MODIFIED="1435149631928" TEXT="http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1435149558141" ID="ID_323633101" MODIFIED="1435149631928" TEXT="http://linuxdownload.adobe.com/linux/x86_64/adobe-release-x86_64-1.0-1.noarch.rpm">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1435149581216" ID="ID_562994264" MODIFIED="1435149631929" TEXT="flash-plugin ">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1435149587128" ID="ID_1847608822" MODIFIED="1435149631929" TEXT="icedtea-web ">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1435149595780" ID="ID_1236401113" MODIFIED="1435149631930" TEXT="vlc smplayer ffmpeg HandBrake-{gui,cli}">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1435149602108" ID="ID_1982783545" MODIFIED="1435149631930" TEXT="libdvdcss gstreamer{,1}-plugins-ugly gstreamer-plugins-bad-nonfree gstreamer1-plugins-bad-freeworld">
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
</node>
</node>
<node COLOR="#0033ff" CREATED="1545599162979" ID="ID_1855731985" MODIFIED="1545599164579" POSITION="left" TEXT="arm">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1545599123116" ID="ID_1927263924" LINK="http://isoredirect.centos.org/altarch/7/isos/armhfp" MODIFIED="1545599166582" TEXT="Downloads">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
<node COLOR="#00b439" CREATED="1542472702994" ID="ID_1640433928" LINK="https://wiki.centos.org/SpecialInterestGroup/AltArch" MODIFIED="1545599168113" TEXT="AltArch">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
<node COLOR="#00b439" CREATED="1542472731826" ID="ID_812210732" LINK="https://wiki.centos.org/SpecialInterestGroup/AltArch/armhfp?action=show&amp;redirect=SpecialInterestGroup%2FAltArch%2FArm32" MODIFIED="1545599170941" TEXT="armhfp">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
</node>
</node>
</map>
