<map version="1.0.1">
<!-- To view this file, download free mind mapping software FreeMind from http://freemind.sourceforge.net -->
<node COLOR="#000000" CREATED="1421503196583" ID="ID_1462460097" LINK="System%20Administration.mm" MODIFIED="1421503224521" TEXT="CentOS">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="20"/>
<hook NAME="accessories/plugins/AutomaticLayout.properties"/>
<node COLOR="#0033ff" CREATED="1435149627724" ID="ID_239994505" MODIFIED="1436107961199" POSITION="right" TEXT="7">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1455721358841" ID="ID_1837839639" MODIFIED="1455721365200" TEXT="Virtualization">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1440935783891" ID="ID_1073361687" LINK="https://wiki.centos.org/HowTos/KVM" MODIFIED="1542314086665" TEXT="KVM">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1440935801911" ID="ID_1584462684" MODIFIED="1455721373003" TEXT="yum -y install @virt* dejavu-lgc-* xorg-x11-xauth tigervnc libguestfs-tools policycoreutils-python bridge-utils">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1440935894261" ID="ID_1265264002" MODIFIED="1455721373003" TEXT="semanage fcontext -a -t virt_image_t &quot;/vm(/.*)?&quot;; restorecon -R /vm ">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1440935899397" ID="ID_5451815" MODIFIED="1455721373003" TEXT="sed -i &apos;s/^\(net.ipv4.ip_forward =\).*/\1 1/&apos; /etc/sysctl.conf; sysctl -p ">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1440935905461" ID="ID_923208888" MODIFIED="1455721373004" TEXT="chkconfig libvirtd on; shutdown -r now">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1440935918209" ID="ID_1521732607" MODIFIED="1455721373004">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      chkconfig network on
    </p>
    <p>
      service network restart
    </p>
    <p>
      yum -y erase NetworkManager
    </p>
    <p>
      cp -p /etc/sysconfig/network-scripts/ifcfg-{eth0,br0}
    </p>
    <p>
      sed -i -e'/HWADDR/d' -e'/UUID/d' -e's/eth0/br0/' -e's/Ethernet/Bridge/' \
    </p>
    <p>
      /etc/sysconfig/network-scripts/ifcfg-br0
    </p>
    <p>
      echo DELAY=0 &gt;&gt; /etc/sysconfig/network-scripts/ifcfg-br0
    </p>
    <p>
      echo 'BOOTPROTO=&quot;none&quot;' &gt;&gt; /etc/sysconfig/network-scripts/ifcfg-eth0
    </p>
    <p>
      echo BRIDGE=br0 &gt;&gt; /etc/sysconfig/network-scripts/ifcfg-eth0
    </p>
    <p>
      service network restart
    </p>
    <p>
      brctl show
    </p>
  </body>
</html></richcontent>
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1465755894279" ID="ID_808865391" MODIFIED="1465755895427" TEXT="ifcfg-bridge0">
<node COLOR="#111111" CREATED="1447880029582" ID="ID_1851330091" MODIFIED="1447880034449">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      DEVICE=&quot;bridge0&quot;
    </p>
    <p>
      ONBOOT=&quot;yes&quot;
    </p>
    <p>
      BOOTPROTO=dhcp
    </p>
    <p>
      TYPE=Bridge
    </p>
    <p>
      NM_CONTROLLED=NO
    </p>
    <p>
      DELAY=0
    </p>
  </body>
</html></richcontent>
</node>
</node>
<node COLOR="#111111" CREATED="1465755911907" ID="ID_317123593" MODIFIED="1465755916634" TEXT="ifcfg-enp11s0">
<node COLOR="#111111" CREATED="1447880004642" ID="ID_201594783" MODIFIED="1447880014393">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      # Generated by dracut initrd
    </p>
    <p>
      NAME=&quot;enp11s0&quot;
    </p>
    <p>
      DEVICE=&quot;enp11s0&quot;
    </p>
    <p>
      ONBOOT=yes
    </p>
    <p>
      NETBOOT=yes
    </p>
    <p>
      UUID=&quot;d017778c-b91f-4853-8393-d014d24f5229&quot;
    </p>
    <p>
      IPV6INIT=yes
    </p>
    <p>
      BOOTPROTO=dhcp
    </p>
    <p>
      TYPE=Ethernet
    </p>
    <p>
      BRIDGE=bridge0
    </p>
    <p>
      NM_CONTROLLED=NO
    </p>
  </body>
</html></richcontent>
</node>
</node>
</node>
<node COLOR="#111111" CREATED="1453042290286" ID="ID_772163710" MODIFIED="1469457654447" TEXT="/var/lib/libvirt/images">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1457553520299" ID="ID_1400430680" MODIFIED="1469457654447" TEXT="/etc/libvirt/qemu/autostart">
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
<node COLOR="#990000" CREATED="1455210403008" ID="ID_1408661389" MODIFIED="1455721373011" TEXT="Xen">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1455222440581" ID="ID_1905169088" MODIFIED="1455721373011" TEXT="Installation">
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1455210412860" ID="ID_1613490466" MODIFIED="1455222449844" TEXT="yum install centos-release-xen">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1455210420840" ID="ID_807023945" MODIFIED="1455222449844" TEXT="yum update">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1455210428036" ID="ID_960890306" MODIFIED="1455222449845" TEXT="yum install xen">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1455211197001" ID="ID_655969713" MODIFIED="1455222449845" TEXT="yum install libvirt">
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
<node COLOR="#111111" CREATED="1455225230765" ID="ID_224162066" MODIFIED="1455721373011" TEXT="Errors">
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1455222445005" ID="ID_357409181" MODIFIED="1455225233773" TEXT="tail -f /var/log/libvirt/libxl/libxl-driver.log">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1455225235577" ID="ID_724960868" MODIFIED="1455225237745" TEXT="ERROR    internal error: libxenlight failed to create new domain &apos;centos-workstation-xen&apos;"/>
</node>
<node COLOR="#111111" CREATED="1466965563882" ID="ID_568444465" MODIFIED="1466965566462" TEXT="auto start">
<node COLOR="#111111" CREATED="1466965579414" ID="ID_1955488647" MODIFIED="1466965581176" TEXT="/etc/xen/auto"/>
</node>
</node>
<node COLOR="#990000" CREATED="1440504140480" ID="ID_423703538" MODIFIED="1455721373013" TEXT="Docker">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1440504201607" ID="ID_1758153499" LINK="http://www.liquidweb.com/kb/how-to-install-docker-on-centos-7/" MODIFIED="1542314148180" TEXT="Install">
<font NAME="SansSerif" SIZE="12"/>
<node COLOR="#111111" CREATED="1440504148588" ID="ID_812096522" MODIFIED="1440504214436" TEXT="yum -y install docker docker-registry">
<font NAME="SansSerif" SIZE="12"/>
<icon BUILTIN="full-1"/>
</node>
<node COLOR="#111111" CREATED="1440504159875" ID="ID_1122722986" MODIFIED="1440504215872" TEXT="systemctl enable docker.service">
<font NAME="SansSerif" SIZE="12"/>
<icon BUILTIN="full-2"/>
</node>
<node COLOR="#111111" CREATED="1440504165083" ID="ID_63869001" MODIFIED="1440504217367" TEXT="systemctl start docker.service">
<font NAME="SansSerif" SIZE="12"/>
<icon BUILTIN="full-3"/>
</node>
<node COLOR="#111111" CREATED="1440504172239" ID="ID_432510743" MODIFIED="1440504220555" TEXT="systemctl status docker.service">
<font NAME="SansSerif" SIZE="12"/>
<icon BUILTIN="full-4"/>
</node>
</node>
</node>
</node>
<node COLOR="#00b439" CREATED="1455721376896" ID="ID_1664993921" MODIFIED="1542314128199" TEXT="chrome">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1455721410480" ID="ID_1896776134" MODIFIED="1455721424314" TEXT="yum install https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm -y">
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
<node COLOR="#00b439" CREATED="1436107963555" ID="ID_1733189226" MODIFIED="1436107971854" TEXT="nmcli d">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
</node>
<node COLOR="#0033ff" CREATED="1435149640460" ID="ID_875080470" LINK="http://wiki.centos.org/TipsAndTricks/MultimediaOnCentOS7" MODIFIED="1542314057927" POSITION="left" TEXT="multimedia">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1435149562817" ID="ID_1996954012" MODIFIED="1455210394925" TEXT="yum">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1435149621372" ID="ID_1246307121" MODIFIED="1455210394925" TEXT="groupinstall">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1435151021179" ID="ID_59726647" MODIFIED="1435151023289" TEXT="&apos;KDE Plasma Workspaces&apos;"/>
</node>
<node COLOR="#990000" CREATED="1435149565028" ID="ID_709786252" MODIFIED="1455210394926" TEXT="install">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1435149550777" ID="ID_312291180" MODIFIED="1435149631928" TEXT="http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1435149558141" ID="ID_323633101" MODIFIED="1435149631928" TEXT="http://linuxdownload.adobe.com/linux/x86_64/adobe-release-x86_64-1.0-1.noarch.rpm">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1435149581216" ID="ID_562994264" MODIFIED="1435149631929" TEXT="flash-plugin ">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1435149587128" ID="ID_1847608822" MODIFIED="1435149631929" TEXT="icedtea-web ">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1435149595780" ID="ID_1236401113" MODIFIED="1435149631930" TEXT="vlc smplayer ffmpeg HandBrake-{gui,cli}">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1435149602108" ID="ID_1982783545" MODIFIED="1435149631930" TEXT="libdvdcss gstreamer{,1}-plugins-ugly gstreamer-plugins-bad-nonfree gstreamer1-plugins-bad-freeworld">
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
</node>
</node>
</node>
</map>
