<map version="1.0.1">
<!-- To view this file, download free mind mapping software FreeMind from http://freemind.sourceforge.net -->
<node COLOR="#000000" CREATED="1324994152442" ID="ID_615331716" LINK="Virtualization.mm" MODIFIED="1543855384274" TEXT="Xen">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="20"/>
<hook NAME="accessories/plugins/AutomaticLayout.properties"/>
<node COLOR="#0033ff" CREATED="1324994187314" ID="ID_18904243" MODIFIED="1324994196901" POSITION="left" TEXT="Multiple Network Cards">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1324994198596" ID="ID_434431264" MODIFIED="1324994203128" TEXT="Continue using eth0">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1324994234235" ID="ID_497792100" MODIFIED="1324994236712" TEXT="/etc/xen/xend-config.sxp">
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1324994245746" ID="ID_332272340" MODIFIED="1324994247976" TEXT="(network-script &apos;network-bridge netdev=eth0 bridge=xenbr0&apos;)"/>
</node>
</node>
</node>
<node COLOR="#0033ff" CREATED="1458986419220" ID="ID_342396211" MODIFIED="1458986421272" POSITION="right" TEXT="Version">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1458986422788" ID="ID_76159418" MODIFIED="1458986425344" TEXT="xl info">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
</node>
<node COLOR="#0033ff" CREATED="1447437331620" ID="ID_24361325" MODIFIED="1447773226388" POSITION="right" TEXT="tail -f /var/log/libvirt/libxl/libxl-driver.log">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
</node>
<node COLOR="#0033ff" CREATED="1454436268038" ID="ID_770583857" MODIFIED="1454436272482" POSITION="right" TEXT="tail -f /var/log/xen/xend.log">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
</node>
<node COLOR="#0033ff" CREATED="1528200227519" ID="ID_1966663290" MODIFIED="1528200236239" POSITION="right" TEXT="Out of space">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font BOLD="true" ITALIC="true" NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1528200237521" ID="ID_143260922" MODIFIED="1528200269092" TEXT="reboot into a non-Xen kernel">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<icon BUILTIN="full-1"/>
</node>
<node COLOR="#00b439" CREATED="1528200250569" ID="ID_1202985466" MODIFIED="1528200270762" TEXT="rm -rf /var/lib/xenstored/tdb*">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<icon BUILTIN="full-2"/>
</node>
<node COLOR="#00b439" CREATED="1528200259574" ID="ID_518604940" MODIFIED="1528200272467" TEXT="reboot into a Xen kernel">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<icon BUILTIN="full-3"/>
</node>
</node>
<node COLOR="#0033ff" CREATED="1447438872022" ID="ID_620470296" MODIFIED="1447773221682" POSITION="right" TEXT="Bridge">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1447438875386" ID="ID_1936218712" MODIFIED="1447438895090" TEXT="ifcfg-e[val]">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1447438909998" ID="ID_1448235608" MODIFIED="1447438916066">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      # Generated by dracut initrd
    </p>
    <p>
      NAME=&quot;enp3s14&quot;
    </p>
    <p>
      DEVICE=&quot;enp3s14&quot;
    </p>
    <p>
      ONBOOT=yes
    </p>
    <p>
      NETBOOT=yes
    </p>
    <p>
      UUID=&quot;3e381a96-d3c2-4f0e-aea2-c64cb2ee0d8a&quot;
    </p>
    <p>
      IPV6INIT=yes
    </p>
    <p>
      TYPE=Ethernet
    </p>
    <p>
      BRIDGE=bridge0
    </p>
  </body>
</html></richcontent>
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
<node COLOR="#00b439" CREATED="1447438919126" ID="ID_1417216806" MODIFIED="1447438925738" TEXT="ifcfg-bridge0">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1447438936610" ID="ID_719002344" MODIFIED="1447438945435">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      DEVICE=&quot;bridge0&quot;
    </p>
    <p>
      ONBOOT=&quot;yes&quot;
    </p>
    <p>
      BOOTPROTO=dhcp
    </p>
    <p>
      TYPE=Bridge
    </p>
  </body>
</html></richcontent>
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
</node>
<node COLOR="#0033ff" CREATED="1530796145650" ID="ID_1045093944" MODIFIED="1530796149723" POSITION="right" TEXT="Guest disk">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1326646097429" ID="ID_779496107" MODIFIED="1530796161988" TEXT="List">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1326646270300" ID="ID_1056154076" MODIFIED="1530796154277" TEXT="commands">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1326646104281" ID="ID_1651877953" MODIFIED="1530796154278" TEXT="kpartx -l [path to vm]">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
<node COLOR="#990000" CREATED="1326646276369" ID="ID_1347573493" MODIFIED="1530796154279" TEXT="examples">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1326646124948" ID="ID_1966368659" MODIFIED="1530796154279" TEXT="kpartx -l /virt/xen/i386/fedora-workstation-disk0">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
</node>
<node COLOR="#00b439" CREATED="1326646073650" ID="ID_770538721" MODIFIED="1530796164940" TEXT="Mount">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1326646280527" ID="ID_1250415172" MODIFIED="1530796154283" TEXT="commands">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1326646142588" ID="ID_1199924539" MODIFIED="1530796154283" TEXT="kpartx -a [full path to vm]">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1326646190916" ID="ID_1362804861" MODIFIED="1530796154284" TEXT="mount /dev/mapper/[loop device] [local mount point] -t [file system type]">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
<node COLOR="#990000" CREATED="1326646286251" ID="ID_350293835" MODIFIED="1530796154285" TEXT="examples">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1326646320446" ID="ID_1351666150" MODIFIED="1530796154285" TEXT="kpartx -a /virt/xen/i386/fedora-workstation-disk0">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1326646342282" ID="ID_977062734" MODIFIED="1530796154286" TEXT="mkdir -p /mnt/tmp">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1326646331094" ID="ID_1358932894" MODIFIED="1530796154286" TEXT="mount /dev/mapper/loop2p3 /mnt/tmp/ -t ext3">
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
</node>
<node COLOR="#00b439" CREATED="1326646161833" ID="ID_1551072644" MODIFIED="1530796167926" TEXT="Unmount">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1326646302786" ID="ID_1909646948" MODIFIED="1530796154290" TEXT="commands">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1326646190916" ID="ID_199813141" MODIFIED="1530796154291" TEXT="umount [local mount point]">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1326646142588" ID="ID_318016545" MODIFIED="1530796154291" TEXT="kpartx -d [full path to vm]">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
<node COLOR="#990000" CREATED="1326646307051" ID="ID_1256761687" MODIFIED="1530796154292" TEXT="examples">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1326646361104" ID="ID_1666637680" MODIFIED="1530796154293" TEXT="umount /mnt/tmp/">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1326646364113" ID="ID_292567219" MODIFIED="1530796154293" TEXT="kpartx -d /virt/xen/i386/fedora-workstation-disk0">
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
</node>
</node>
<node COLOR="#0033ff" CREATED="1344706333490" ID="ID_69320040" MODIFIED="1344706338633" POSITION="right" TEXT="Security">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1344706343745" ID="ID_734927625" MODIFIED="1344706355111" TEXT="/boot/grub.conf">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1344706412763" ID="ID_1525442431" MODIFIED="1344706426454" TEXT="kernel /xen.gz-2.6.18-308.11.1.el5.centos.plus allow_unsafe">
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
</node>
<node COLOR="#0033ff" CREATED="1364070346382" ID="ID_1681105795" MODIFIED="1364070358951" POSITION="right" TEXT="WOL">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1364070376119" ID="ID_1021222975" MODIFIED="1364070379919" TEXT="/etc/rc.d/init.d/xend">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1364070397115" ID="ID_441387877" MODIFIED="1364070427861">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      Add the following line:
    </p>
    <p>
      /etc/xen/scripts/network-bridge stop
    </p>
    <p>
      before the line:
    </p>
    <p>
      /usr/sbin/xend stop
    </p>
  </body>
</html></richcontent>
<font NAME="SansSerif" SIZE="14"/>
</node>
<node COLOR="#990000" CREATED="1364070614983" ID="ID_1249789845" MODIFIED="1364216426082" TEXT=" /etc/sysconfig/network-scripts/ifcfg-eth0">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1364070621012" ID="ID_1771011197" MODIFIED="1364216426082" TEXT="ETHTOOL_OPTS=&quot;wol g&quot;">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
</node>
</node>
<node COLOR="#0033ff" CREATED="1468931228499" ID="ID_1136415176" LINK="https://wiki.centos.org/HowTos/Grub2" MODIFIED="1542306350763" POSITION="right" TEXT="Change dom0 memory">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1468931239731" ID="ID_1523826180" MODIFIED="1468931306222" TEXT="/etc/default/grub">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<icon BUILTIN="full-1"/>
<node COLOR="#990000" CREATED="1468931242971" ID="ID_969586840" MODIFIED="1468931296004">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      GRUB_CMDLINE_XEN_DEFAULT=&quot;dom0_mem=<b><i>[min]</i></b>M,max:<b><i>[max]</i></b>M&quot;
    </p>
  </body>
</html></richcontent>
<font NAME="SansSerif" SIZE="14"/>
</node>
<node COLOR="#990000" CREATED="1468931262315" ID="ID_432574290" MODIFIED="1468931268055" TEXT="GRUB_CMDLINE_XEN_DEFAULT=&quot;dom0_mem=512M,max:512M&quot;">
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
<node COLOR="#00b439" CREATED="1468931307123" ID="ID_1316371121" MODIFIED="1468931314627" TEXT="grub2-mkconfig -o /boot/grub2/grub.cfg">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<icon BUILTIN="full-2"/>
</node>
<node COLOR="#00b439" CREATED="1527183199579" ID="ID_1626295235" MODIFIED="1527183203747" TEXT="grep &quot;^menuentry&quot; /boot/grub2/grub.cfg | cut -d &quot;&apos;&quot; -f2">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<icon BUILTIN="full-3"/>
</node>
<node COLOR="#00b439" CREATED="1527183219588" ID="ID_521672350" MODIFIED="1527183225585" TEXT="grub2-set-default &apos;CentOS Linux, with Xen hypervisor&apos;">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<icon BUILTIN="full-4"/>
</node>
</node>
<node COLOR="#0033ff" CREATED="1532520916772" ID="ID_1659359593" MODIFIED="1546026291498" POSITION="right" TEXT="Install VM w/ virsh">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1532521110842" ID="ID_932237133" MODIFIED="1532521117174" TEXT="Fedora 28">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1532520945072" ID="ID_737211005" MODIFIED="1532521119370">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      virt-install \
    </p>
    <p>
      --connect xen:/// \
    </p>
    <p>
      --paravirt \
    </p>
    <p>
      --name fedora-28-xen \
    </p>
    <p>
      --ram 2048 \
    </p>
    <p>
      --disk size=20 \
    </p>
    <p>
      --vcpus 2 \
    </p>
    <p>
      --os-type linux \
    </p>
    <p>
      --os-variant virtio26 \
    </p>
    <p>
      --network bridge=bridge0 \
    </p>
    <p>
      --graphics none \
    </p>
    <p>
      --location 'http://192.168.168.31/cblr/links/Fedora-28-x86_64/' \
    </p>
    <p>
      --extra-args 'text console=ttyS0 utf8 console=hvc0'
    </p>
  </body>
</html></richcontent>
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
</node>
<node COLOR="#990000" CREATED="1532521161742" ID="ID_290883090" MODIFIED="1544837591458">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      virt-install \
    </p>
    <p>
      --connect xen:/// \
    </p>
    <p>
      --paravirt \
    </p>
    <p>
      --name workstation \
    </p>
    <p>
      --ram 3192 \
    </p>
    <p>
      --disk size=25 \
    </p>
    <p>
      --vcpus 2 \
    </p>
    <p>
      --os-type linux \
    </p>
    <p>
      --os-variant virtio26 \
    </p>
    <p>
      --network bridge=bridge0 \
    </p>
    <p>
      --graphics vga \
    </p>
    <p>
      --location 'http://192.168.168.32/cblr/links/Fedora-28-x86_64/' \
    </p>
    <p>
      --extra-args 'ks=http://192.168.168.32/kickstart/workstation.ks text console=ttyS0 utf8 console=hvc0'
    </p>
  </body>
</html></richcontent>
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
<node COLOR="#00b439" CREATED="1532521121578" ID="ID_153645207" MODIFIED="1532521123358" TEXT="Atomic">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1532521125202" ID="ID_1574468395" MODIFIED="1532521126934" TEXT="CentOS">
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1532521038462" ID="ID_788390219" MODIFIED="1544837579659">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      virt-install \
    </p>
    <p>
      --connect xen:/// \
    </p>
    <p>
      --paravirt \
    </p>
    <p>
      --name centos-7-xen \
    </p>
    <p>
      --ram 2048 \
    </p>
    <p>
      --disk size=20 \
    </p>
    <p>
      --vcpus 2 \
    </p>
    <p>
      --os-type linux \
    </p>
    <p>
      --os-variant virtio26 \
    </p>
    <p>
      --network bridge=bridge0 \
    </p>
    <p>
      --graphics vga \
    </p>
    <p>
      --location 'http://192.168.168.31/cblr/links/CentOS-7-Atomic-x86_64/' \
    </p>
    <p>
      --extra-args 'ks=http://192.168.168.32/kickstart/centos-7-atomic.ks text console=ttyS0 utf8 console=hvc0'
    </p>
  </body>
</html></richcontent>
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
<node COLOR="#990000" CREATED="1532521127314" ID="ID_715338360" MODIFIED="1532521128530" TEXT="RHEL">
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1532521086062" ID="ID_1945523968" MODIFIED="1544837601667">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      virt-install \
    </p>
    <p>
      --connect xen:/// \
    </p>
    <p>
      --paravirt \
    </p>
    <p>
      --name rhel-7-atomic-xen \
    </p>
    <p>
      --ram 2048 \
    </p>
    <p>
      --disk size=20 \
    </p>
    <p>
      --vcpus 2 \
    </p>
    <p>
      --os-type linux \
    </p>
    <p>
      --os-variant virtio26 \
    </p>
    <p>
      --network bridge=bridge0 \
    </p>
    <p>
      --graphics vga \
    </p>
    <p>
      --location 'http://192.168.168.32/cblr/links/RHEL-7-Atomic-x86_64/' \
    </p>
    <p>
      --extra-args 'ks=http://192.168.168.32/kickstart/centos-7-atomic.ks text console=ttyS0 utf8 console=hvc0'
    </p>
  </body>
</html></richcontent>
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
</node>
</node>
<node COLOR="#0033ff" CREATED="1453042282830" ID="ID_1391008699" MODIFIED="1469457571690" POSITION="left" TEXT="VM">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1453042299886" ID="ID_420427733" MODIFIED="1469457566619" TEXT="/var/lib/xen/images">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
<node COLOR="#00b439" CREATED="1457553578494" ID="ID_1500844024" MODIFIED="1469457566619" TEXT="/etc/libvirt/libxl/autostart">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
<node COLOR="#00b439" CREATED="1449955862961" ID="ID_85903213" MODIFIED="1469457591725" TEXT="Configuration">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1449955881110" ID="ID_860435509" MODIFIED="1469457591725" TEXT="/etc/libvirt/libxl">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
</node>
<node COLOR="#0033ff" CREATED="1466965563882" ID="ID_568444465" MODIFIED="1545598892130" POSITION="left" TEXT="auto start">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1466965579414" ID="ID_1955488647" MODIFIED="1545598892136" TEXT="/etc/xen/auto">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
</node>
<node COLOR="#0033ff" CREATED="1455225230765" ID="ID_224162066" MODIFIED="1545598942293" POSITION="left" TEXT="Errors">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1455222445005" ID="ID_357409181" MODIFIED="1545598942294" TEXT="tail -f /var/log/libvirt/libxl/libxl-driver.log">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
<node COLOR="#00b439" CREATED="1455225235577" ID="ID_724960868" MODIFIED="1545598942294" TEXT="ERROR    internal error: libxenlight failed to create new domain &apos;centos-workstation-xen&apos;">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
</node>
<node COLOR="#0033ff" CREATED="1458646904966" ID="ID_228196213" MODIFIED="1545598980293" POSITION="left" TEXT="/etc/libvirt/libxl/autostart">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
</node>
</node>
</map>
